// vue/src/App.vue
<template>
  <header>
  <!-- <a class="logo" href="/"><img src="images/logo.svg" alt="logo"></a> -->
  <nav>
    <ul class="nav__links">
      <li><a routerLink="/index">Strona Głowna</a></li>
      <li><a routerLink="/calendar">Kalendarz</a></li>
      <li><router-link to="/login">log in / logout</router-link></li>
      <li class="profile"><a href="#"><img class="photo-profile" src="./assets/avatar.png"/></a></li>
    </ul>
  </nav>
  <!-- <a class="cta" href="#">Contact</a> -->
  <p class="menu cta">Menu</p>
</header>
<div id="mobile__menu" class="overlay">
  <a class="close">&times;</a>
  <div class="overlay__content">
    <li><a href="#"><img src="./assets/avatar.png"/></a></li>
    <li><a routerLink="/index">Strona Główna</a></li>
    <li><a routerLink="/calendar">Kalendarz</a></li>
    <li><a routerLink="/login">Log in / logout</a></li>
  </div>
</div>
  <router-view></router-view>
</template>

<script>
export default {
  name: 'App',
}
</script>

<style>
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 30px 10%;
  background-color: #414064;
}

.logo {
  cursor: pointer;
  order: 3;
  margin-left: auto;
}

nav {
  order: 1;
}

.nav__links a,
.cta,
.overlay__content a {
  font-family: "Montserrat", sans-serif;
  font-weight: 500;
  color: #edf0f1;
  text-decoration: none;
}

.nav__links {
  list-style: none;
  display: flex;
  font-size: 16px;
}

.nav__links li {
  padding: 0px 20px;
}

.nav__links li:nth-child(1) {
  padding: 0 20px 0 0;
}

.nav__links li a {
  transition: all 0.3s ease 0s;
}

.nav__links li a:hover {
  color: #0088a9;
}

.cta {
  order: 2;
  margin-left: 20px;
  padding: 9px 25px;
  background-color: rgba(0, 136, 169, 1);
  border: none;
  border-radius: 50px;
  cursor: pointer;
  transition: all 0.3s ease 0s;
}

.cta:hover {
  background-color: rgba(0, 136, 169, 0.8);
}

/* Mobile Nav */

.menu {
  display: none;
}

.overlay {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  left: 0;
  top: 0;
  background-color: #414064;
  overflow-x: hidden;
  transition: all 0.5s ease 0s;
}

.overlay--active {
  width: 100%;
  z-index: 3;
}

.overlay__content {
  display: flex;
  height: 100%;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.overlay a {
  padding: 15px;
  font-size: 36px;
  display: block;
  transition: all 0.3s ease 0s;
}

.overlay a:hover,
.overlay a:focus {
  color: #0088a9;
}
.overlay .close {
  position: absolute;
  top: 20px;
  right: 45px;
  font-size: 60px;
  color: #edf0f1;
}

@media screen and (max-height: 450px) {
  .overlay a {
    font-size: 20px;
  }
  .overlay .close {
    font-size: 40px;
    top: 15px;
    right: 35px;
  }
}

@media only screen and (max-width: 800px) {
  .nav__links,
  .cta {
    display: none;
  }
  .menu {
    display: initial;
  }
}

.profile {
  position: absolute;
  right: 30px;
  top: 24px;
}

.photo-profile {
  width: 30px;
}

</style>

// angular/src/app/app.component.ts
import { Component, ElementRef, Renderer2 } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular';

  constructor(private elementRef: ElementRef, private renderer: Renderer2) { }

  ngAfterViewInit() {
    const menuOpen = this.elementRef.nativeElement.querySelector(".menu");
    const menuClose = this.elementRef.nativeElement.querySelector(".close");
    const overlay = this.elementRef.nativeElement.querySelector(".overlay");

    this.renderer.listen(menuOpen, 'click', () => {
      this.renderer.addClass(overlay, 'overlay--active');
    });

    this.renderer.listen(menuClose, 'click', () => {
      this.renderer.removeClass(overlay, 'overlay--active');
    });
  }


}

<header>
  <!-- <a class="logo" href="/"><img src="images/logo.svg" alt="logo"></a> -->
  <nav>
    <ul class="nav__links">
      <li><a routerLink="/index">Strona Głowna</a></li>
      <li><a routerLink="/calendar">Kalendarz</a></li>
      <li><a routerLink="/login">log in / logout</a></li>
      <li class="profile"><a href="#"><img src="cos tu bedzie xd"/></a></li>
    </ul>
  </nav>
  <!-- <a class="cta" href="#">Contact</a> -->
  <p class="menu cta">Menu</p>
</header>
<div id="mobile__menu" class="overlay">
  <a class="close">&times;</a>
  <div class="overlay__content">
    <li><a href="#"><img src="tu bedzie jakies zdj oznaczajace profil xd"/></a></li>
    <li><a routerLink="/index">Strona Główna</a></li>
    <li><a routerLink="/calendar">Kalendarz</a></li>
    <li><a routerLink="/login">Log in / logout</a></li>
  </div>
</div>
<div>

  <router-outlet></router-outlet>
